/**
 * URL utilities for BYAN platform config.
 *
 * stripApiSuffix : normalize apiUrl so the MCP server.js doesn't double the
 *                  /api prefix (see install B5 bugfix).
 * buildAuthHeader : ApiKey scheme for user-generated byan_ tokens,
 *                   Bearer scheme for JWT tokens.
 */

function stripApiSuffix(url) {
  if (typeof url !== 'string' || url.length === 0) return url;
  // Strip trailing /api, /api/, /api/v1, /api/v1/ etc. — keep protocol/host intact.
  return url.replace(/\/api(?:\/v\d+)?\/?$/, '');
}

function buildAuthHeader(token) {
  if (!token || typeof token !== 'string' || token.length === 0) {
    return {};
  }
  const scheme = token.startsWith('byan_') ? 'ApiKey' : 'Bearer';
  return { Authorization: `${scheme} ${token}` };
}

module.exports = {
  stripApiSuffix,
  buildAuthHeader,
};
