#!/bin/bash
# BYAN Installer Script
# Version: 1.0.0
# Compatible: GitHub Copilot CLI, VSCode, Claude Code, Codex

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
BYAN_VERSION="1.0.0"
PROJECT_ROOT="$(pwd)"
BMAD_DIR="${PROJECT_ROOT}/_bmad"
INSTALL_DIR="${BMAD_DIR}/bmb"

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║   🏗️  BYAN INSTALLER v${BYAN_VERSION}                        ║"
echo "║   Builder of YAN - Agent Creator                          ║"
echo "║                                                            ║"
echo "║   Methodology: Merise Agile + TDD + 64 Mantras           ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if running in project directory
if [ ! -d ".git" ] && [ ! -f "package.json" ] && [ ! -f "pyproject.toml" ]; then
    echo -e "${YELLOW}⚠️  Warning: Not in a recognized project directory${NC}"
    echo "BYAN works best when installed in a project with version control."
    echo ""
    read -p "Continue anyway? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 1
    fi
fi

# Step 1: Detect platform
echo -e "${BLUE}[1/7] Detecting platform...${NC}"

PLATFORM=""
if command -v gh &> /dev/null && gh copilot --version &> /dev/null 2>&1; then
    PLATFORM="copilot"
    echo -e "${GREEN}✓ GitHub Copilot CLI detected${NC}"
elif command -v code &> /dev/null; then
    PLATFORM="vscode"
    echo -e "${GREEN}✓ VSCode detected${NC}"
elif command -v claude &> /dev/null; then
    PLATFORM="claude"
    echo -e "${GREEN}✓ Claude Code detected${NC}"
else
    echo -e "${YELLOW}⚠️  No specific platform detected${NC}"
    echo "Select platform to install for:"
    echo "1) GitHub Copilot CLI"
    echo "2) VSCode"
    echo "3) Claude Code"
    echo "4) Codex"
    echo "5) All platforms"
    read -p "Choice (1-5): " platform_choice
    
    case $platform_choice in
        1) PLATFORM="copilot";;
        2) PLATFORM="vscode";;
        3) PLATFORM="claude";;
        4) PLATFORM="codex";;
        5) PLATFORM="all";;
        *) echo "Invalid choice"; exit 1;;
    esac
fi

# Step 2: Create directory structure
echo -e "${BLUE}[2/7] Creating directory structure...${NC}"

mkdir -p "${BMAD_DIR}"/{bmb,core,_config,_memory,_output}
mkdir -p "${INSTALL_DIR}"/{agents,workflows/byan/{steps,templates,data},config}

echo -e "${GREEN}✓ Directories created${NC}"

# Step 3: Download/Install BYAN files
echo -e "${BLUE}[3/7] Installing BYAN files...${NC}"

# Check if we're in the conception directory (development mode)
if [ -f "${PROJECT_ROOT}/_bmad/bmb/agents/byan.md" ]; then
    echo -e "${YELLOW}Development mode: Using local files${NC}"
    # Files already exist, skip download
else
    # In production, we would download from GitHub/NPM
    echo -e "${YELLOW}Note: In production, files would be downloaded from repository${NC}"
    echo "For now, please ensure BYAN files are present in _bmad/bmb/"
fi

# Step 4: Create config
echo -e "${BLUE}[4/7] Configuring BYAN...${NC}"

read -p "Your name: " USER_NAME
read -p "Communication language (Francais/English): " COMM_LANG

cat > "${INSTALL_DIR}/config.yaml" <<EOF
# BMB Module Configuration
# Generated by BYAN installer
# Version: ${BYAN_VERSION}
# Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

bmb_creations_output_folder: "{project-root}/_bmad-output/bmb-creations"

# Core Configuration Values
user_name: ${USER_NAME}
communication_language: ${COMM_LANG}
document_output_language: ${COMM_LANG}
output_folder: "{project-root}/_bmad-output"

# Platform
platform: ${PLATFORM}
EOF

echo -e "${GREEN}✓ Configuration created${NC}"

# Step 5: Install dependencies (if needed)
echo -e "${BLUE}[5/7] Checking dependencies...${NC}"

if [ "$PLATFORM" = "copilot" ]; then
    if ! command -v gh &> /dev/null; then
        echo -e "${RED}✗ GitHub CLI not found${NC}"
        echo "Please install: https://cli.github.com/"
        exit 1
    fi
    echo -e "${GREEN}✓ GitHub CLI installed${NC}"
fi

# Step 6: Create shortcuts/aliases
echo -e "${BLUE}[6/7] Creating shortcuts...${NC}"

# Add byan alias to shell config
SHELL_RC="${HOME}/.bashrc"
if [ -f "${HOME}/.zshrc" ]; then
    SHELL_RC="${HOME}/.zshrc"
fi

if ! grep -q "alias byan=" "${SHELL_RC}" 2>/dev/null; then
    echo "" >> "${SHELL_RC}"
    echo "# BYAN shortcuts" >> "${SHELL_RC}"
    echo "alias byan='cd ${PROJECT_ROOT} && gh copilot suggest \"activate BYAN agent\"'" >> "${SHELL_RC}"
    echo -e "${GREEN}✓ Shell alias created (restart terminal or run: source ${SHELL_RC})${NC}"
else
    echo -e "${YELLOW}⚠️  Alias already exists${NC}"
fi

# Step 7: Verification
echo -e "${BLUE}[7/7] Verifying installation...${NC}"

CHECKS_PASSED=0
CHECKS_TOTAL=5

if [ -d "${INSTALL_DIR}/agents" ]; then
    echo -e "${GREEN}✓ Agents directory exists${NC}"
    ((CHECKS_PASSED++))
fi

if [ -d "${INSTALL_DIR}/workflows/byan" ]; then
    echo -e "${GREEN}✓ Workflows directory exists${NC}"
    ((CHECKS_PASSED++))
fi

if [ -f "${INSTALL_DIR}/config.yaml" ]; then
    echo -e "${GREEN}✓ Configuration file created${NC}"
    ((CHECKS_PASSED++))
fi

if [ -f "${INSTALL_DIR}/agents/byan.md" ]; then
    echo -e "${GREEN}✓ BYAN agent file found${NC}"
    ((CHECKS_PASSED++))
else
    echo -e "${YELLOW}⚠️  BYAN agent file not found (expected in development)${NC}"
fi

if [ -f "${INSTALL_DIR}/workflows/byan/data/mantras.yaml" ]; then
    echo -e "${GREEN}✓ Mantras data file found${NC}"
    ((CHECKS_PASSED++))
else
    echo -e "${YELLOW}⚠️  Mantras file not found (expected in development)${NC}"
fi

echo ""
echo -e "${BLUE}Verification: ${CHECKS_PASSED}/${CHECKS_TOTAL} checks passed${NC}"

# Installation complete
echo ""
echo -e "${GREEN}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║   ✅ BYAN INSTALLATION COMPLETE!                           ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo "Installation Summary:"
echo "  • Platform: ${PLATFORM}"
echo "  • Installation Directory: ${INSTALL_DIR}"
echo "  • Configuration: ${INSTALL_DIR}/config.yaml"
echo "  • User: ${USER_NAME}"
echo "  • Language: ${COMM_LANG}"
echo ""

echo "Next Steps:"
echo ""
echo "1. Activate BYAN:"
if [ "$PLATFORM" = "copilot" ]; then
    echo -e "   ${BLUE}gh copilot suggest 'activate byan agent'${NC}"
    echo "   or use alias: ${BLUE}byan${NC}"
elif [ "$PLATFORM" = "vscode" ]; then
    echo "   Open VSCode Command Palette (Ctrl+Shift+P)"
    echo "   Type: 'Activate BYAN Agent'"
elif [ "$PLATFORM" = "claude" ]; then
    echo -e "   ${BLUE}claude chat --agent byan${NC}"
else
    echo "   Follow your platform's agent activation procedure"
fi

echo ""
echo "2. Create your first agent:"
echo "   [INT] Start Intelligent Interview (30-45 min)"
echo "   [QC] Quick Create (10 min)"
echo ""
echo "3. Explore documentation:"
echo "   • Guide: ${BMAD_DIR}/_bmad-output/guide-reference-rapide-merise-agile-tdd.md"
echo "   • Specs: ${BMAD_DIR}/_bmad-output/specs-byan-agent-creator.md"
echo "   • Mantras: ${INSTALL_DIR}/workflows/byan/data/mantras.yaml"
echo ""

echo "Need help? Type '/bmad-help' when BYAN is active"
echo ""
echo -e "${BLUE}Happy agent building! 🏗️${NC}"
