import fs from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';

// byan-sync-rules generator.
//
// Reads the single source of truth (_byan/_config/strict-mode.yaml) and emits
// the per-platform artifacts that enforce BYAN Strict Mode:
//   - .claude/skills/byan-strict/SKILL.md            (owned, full-file)
//   - .claude/hooks/lib/strict-config.json           (owned, full-file)
//   - AGENTS.md                                       (upsert block, Codex)
//   - .github/copilot-instructions.md                 (upsert block, Copilot)
//
// Owned files are rewritten wholesale (they carry a generated-by header).
// Shared files get a block upserted between BYAN-STRICT markers, leaving the
// rest of the file untouched.

const BEGIN = 'BYAN-STRICT:BEGIN';
const END = 'BYAN-STRICT:END';
const DEFAULT_CONFIG_REL = path.join('_byan', '_config', 'strict-mode.yaml');

export function resolveRoot(projectRoot) {
  return projectRoot || process.env.CLAUDE_PROJECT_DIR || process.cwd();
}

export function loadConfig({ projectRoot, configPath } = {}) {
  const root = resolveRoot(projectRoot);
  const file = configPath || path.join(root, DEFAULT_CONFIG_REL);
  if (!fs.existsSync(file)) {
    throw new Error(`strict-mode config not found at ${file}`);
  }
  const cfg = yaml.load(fs.readFileSync(file, 'utf8'));
  if (!cfg || typeof cfg !== 'object') {
    throw new Error(`strict-mode config at ${file} did not parse to an object`);
  }
  if (!Array.isArray(cfg.mantras) || cfg.mantras.length === 0) {
    throw new Error('strict-mode config must define a non-empty mantras list');
  }
  return cfg;
}

// ---------------------------------------------------------------------------
// Renderers — pure functions config -> string.
// ---------------------------------------------------------------------------

const GENERATED_NOTE =
  'Generated by byan-sync-rules from _byan/_config/strict-mode.yaml. Do not hand-edit.';

export function renderStrictConfig(cfg) {
  return {
    _generated_by: 'byan-sync-rules',
    version: cfg.version,
    min_passes: cfg.self_verify.min_passes,
    last_verdict_must_be: cfg.self_verify.last_verdict_must_be,
    min_score: cfg.confidence.min_score,
    auto_keywords: cfg.activation.auto_keywords,
    completion_claim_markers: cfg.hooks.completion_claim_markers,
    scope_guard: cfg.hooks.scope_guard,
    freshness_window_seconds: cfg.hooks.freshness_window_seconds,
    banners: {
      context: cfg.injection.context_banner,
      stop_block: cfg.injection.stop_block_reason,
      scope_deny: cfg.injection.pretooluse_deny_reason,
    },
  };
}

function mantraLines(cfg) {
  return cfg.mantras
    .map((m) => `- **${m.id} ${m.name}** — ${m.rule.trim()}`)
    .join('\n');
}

// Projects the strict mantras into the shape the MantraValidator consumes
// (mirrors src/byan-v2/data/mantras.json). Lets the pre-commit mantra gate
// score strict artifacts against the strict ruleset instead of the persona one.
export function renderMantrasData(cfg) {
  return {
    metadata: {
      source: 'byan-sync-rules',
      generated_from: '_byan/_config/strict-mode.yaml',
      count: cfg.mantras.length,
    },
    mantras: cfg.mantras.map((m) => ({
      id: m.id,
      title: m.name,
      description: m.rule.trim(),
      validation: {
        type: 'keyword',
        keywords: m.validation_keywords || [m.name.toLowerCase()],
        required: true,
      },
      priority: m.priority || 'high',
    })),
  };
}

export function renderSkill(cfg) {
  const triggers = cfg.activation.auto_keywords
    .map((k) => `\`${k}\``)
    .join(', ');
  return `---
name: byan-strict
description: >-
  ${cfg.description.trim()} Invoke when the user asks for a production
  deliverable, a complete app, a filled contract from a template, or uses
  any activation keyword (${triggers}). Enforces scope-lock, N>=${cfg.self_verify.min_passes}
  self-verify passes, and a 95% confidence floor on hard claims.
allowed-tools:
  - mcp__byan__byan_strict_lock_scope
  - mcp__byan__byan_strict_self_verify
  - mcp__byan__byan_strict_complete
  - mcp__byan__byan_strict_status
  - mcp__byan__byan_strict_abort
---

<!-- ${GENERATED_NOTE} -->

# BYAN Strict Mode

You are operating under BYAN Strict Mode. The user asked for something
complete. Downgrading the scope is the failure this mode exists to prevent.

## Protocol

1. **Lock the scope** with \`byan_strict_lock_scope\` before building. Provide a
   verbatim restatement of the request and testable \`acceptanceCriteria\`. The
   locked scope is the contract.
2. **Build the full scope.** Do not substitute an MVP, a stub, or a simplified
   version. If a part cannot be done, surface it as a gap — do not cut silently.
3. **Self-verify at least ${cfg.self_verify.min_passes} times** with
   \`byan_strict_self_verify\`, re-reading the original request each pass. The
   last pass must report verdict \`ok\`.
4. **Complete** with \`byan_strict_complete\` to earn the audit token. Without it,
   the pre-commit gate blocks the commit.

## Hard claims

Claims in security, performance, or compliance need LEVEL-1 sourcing
(${cfg.confidence.min_score}%) or they are BLOCKED.

## Mantras

${mantraLines(cfg)}
`;
}

export function renderAgentsBlock(cfg) {
  return `## BYAN Strict Mode

${cfg.injection.context_banner.trim()}

The strict tools (\`byan_strict_lock_scope\`, \`byan_strict_self_verify\`,
\`byan_strict_complete\`, \`byan_strict_status\`, \`byan_strict_abort\`) are exposed
by the \`byan\` MCP server. A commit without a fresh, matching audit token is
blocked by the pre-commit gate.

Hard mantras:

${mantraLines(cfg)}`;
}

export function renderCopilotBlock(cfg) {
  // Copilot has no blocking mechanism; this is injection-only guidance.
  return `## BYAN Strict Mode

${cfg.injection.context_banner.trim()}

Use the \`byan\` MCP strict tools to lock scope, self-verify (>= ${cfg.self_verify.min_passes} passes),
and complete. The pre-commit gate is the final net: a commit without a fresh,
matching audit token is rejected.

Hard mantras:

${mantraLines(cfg)}`;
}

// ---------------------------------------------------------------------------
// File operations.
// ---------------------------------------------------------------------------

function ensureDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeIfChanged(filePath, content) {
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (existing === content) return 'unchanged';
  ensureDir(filePath);
  fs.writeFileSync(filePath, content);
  return existing === null ? 'created' : 'updated';
}

// Insert or replace a block delimited by HTML-comment markers. Preserves
// everything outside the markers. If the file does not exist, creates it with
// just the block.
export function upsertBlock({ filePath, block }) {
  const wrapped = `<!-- ${BEGIN} (${GENERATED_NOTE}) -->\n${block}\n<!-- ${END} -->`;
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;

  if (existing === null) {
    ensureDir(filePath);
    fs.writeFileSync(filePath, wrapped + '\n');
    return 'created';
  }

  const re = new RegExp(
    `<!-- ${BEGIN}[\\s\\S]*?${END} -->`,
    'm'
  );
  let next;
  if (re.test(existing)) {
    next = existing.replace(re, wrapped);
  } else {
    next = existing.replace(/\s*$/, '') + '\n\n' + wrapped + '\n';
  }
  if (next === existing) return 'unchanged';
  fs.writeFileSync(filePath, next);
  return existing.includes(BEGIN) ? 'updated' : 'appended';
}

// ---------------------------------------------------------------------------
// Orchestration.
// ---------------------------------------------------------------------------

export function syncRules({ projectRoot, configPath } = {}) {
  const root = resolveRoot(projectRoot);
  const cfg = loadConfig({ projectRoot: root, configPath });

  const report = {};

  const skillPath = path.join(root, '.claude', 'skills', 'byan-strict', 'SKILL.md');
  report['.claude/skills/byan-strict/SKILL.md'] = writeIfChanged(skillPath, renderSkill(cfg));

  const cfgJsonPath = path.join(root, '.claude', 'hooks', 'lib', 'strict-config.json');
  report['.claude/hooks/lib/strict-config.json'] = writeIfChanged(
    cfgJsonPath,
    JSON.stringify(renderStrictConfig(cfg), null, 2) + '\n'
  );

  const agentsPath = path.join(root, 'AGENTS.md');
  report['AGENTS.md'] = upsertBlock({ filePath: agentsPath, block: renderAgentsBlock(cfg) });

  const copilotPath = path.join(root, '.github', 'copilot-instructions.md');
  report['.github/copilot-instructions.md'] = upsertBlock({
    filePath: copilotPath,
    block: renderCopilotBlock(cfg),
  });

  const mantrasPath = path.join(root, 'src', 'byan-v2', 'data', 'strict-mantras.json');
  if (fs.existsSync(path.dirname(mantrasPath))) {
    report['src/byan-v2/data/strict-mantras.json'] = writeIfChanged(
      mantrasPath,
      JSON.stringify(renderMantrasData(cfg), null, 2) + '\n'
    );
  }

  return report;
}

export const MARKERS = { BEGIN, END };
